### PR TITLE
Fix/accordion click event

### LINKED ISSUE #660: Accordion - closes when accordion item is clicked
**Describe the bug**
When an accordion item is expanded and the item's details is clicked, the accordion item closes.

**To Reproduce**
1. Open an accordion section
2. Click on the accordion details (not the accordion title)
3. The accorion section will close

**Expected behavior**
The accordion item should only close when the accordion title is clicked.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version 125.0.6422.61

**Additional context**
The Accordion has an onClick function that is passed down to each accordion item including the AccordionDetails, so when you click on any part of an accordion item, it closes the item.

Please follow these steps to create your branch:
```bash
git checkout release/1.1.0
git pull
git checkout -b 'fix/accordion-click-event'
```

### PR DESCRIPTION
**Pull request by alexsteele95**
Removed (seemingly unnecessary - correct me if I'm wrong!) selected logic and migrated onClick behaviour to the title component so that the click box only effects the title (and not the details).

### CODE REVIEW

**Review by Ibabalola — CHANGES_REQUESTED** [review]
Hi @alexsteele95 , can you add an example of the accordion to the demo page, I've not mistaken it is currently not there.

Screenshot 2024-06-26 at 14 11 07

Looking at the changelog the Accordion component was release in version "1.0.0"

File: src/accordion/AccordionTitle.tsx [hunk 1]
```diff
@@ -26,8 +26,15 @@ export const AccordionTitle = ({
   const { expanded, titleClassName, expandIcon, collapsedIcon } = useContext(AccordionContext);
   const { title } = useContext(AccordionItemContext);
   const titleClasses = classNames([className, titleClassName]);
+  const { onClick } = useContext(AccordionContext);
```
Comment (daniele-zurico) [inline src/accordion/AccordionTitle.tsx:30]: it could be nice to have a test that:
1. make sure that on click on the title it does something
2.on click on the other element does nothing

**Review by Ibabalola — DISMISSED** [review]

**Review by Ibabalola — APPROVED** [review]
